### PR TITLE
[add] git workflow and good pracitices

### PR DESCRIPTION
**Pull request by abdelhak2406**
please suggest the changes you want me to make before merging, i can remake a new pr with another commit message if needed

### CODE REVIEW

**Comment by Abdera7mane** [comment]
The convention is to name the file `CONTRIBUTING.md` not `CONTRIBUTE.md` also try to remove some heavy language x) for the sake to keep the contributing guidelines as friendly as possible

**Comment by cr105ph1nx** [comment]
I've done some edits on it, check it out when you can @abdelhak2406

**Comment by abdelhak2406** [comment]
@cr105ph1nx  looks good for me i'll just change the file name as @Abdera7mane  suggested and i can squash and merge

**Review by cr105ph1nx — COMMENTED** [review]
don't forget that when adding a tutorial to this repo, you need to add it to the table of matters on the README so people can find it easily, other than that everything looks good to me 👏

**Pull request merged**
